version: "3.7"

services:
  os:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    networks:
      - os_share_network
    volumes:
      - ./:/root/SynestiaOS

networks:
  os_share_network:
